### ISSUE TITLE
Is this compatible with macOS?

### ISSUE THREAD

**Issue by vincentmader** [xamut/tmux-network-bandwidth#1]
I just installed this plugin using the tmux package manager. Unfortunately, the up- and downlink speeds are not displayed in the status bar. Is this a problem with the requirements?

I did install awk via homebrew and netstat is installed by default. But as far as I know, numfmt is not available for Mac. There is gnumfmt though, would it be possible to use that instead?

**Comment by ilya-manin** [comment]
Hey @vincentmader, 
I have `numfmt` installed from `coreutils` brew package. So I think that if you install it, everything will work: `brew install coreutils`

If this doesn't help, feel free to write me back.

**Comment by vincentmader** [comment]
I was pretty sure I had already installed `coreutils`... Anyways, I executed `brew install coreutils` again to be sure and now the up- and downlink speeds are displayed correctly! Thank you very much.
