### ISSUE TITLE
not working on Debian 10 (Buster )

### ISSUE THREAD

**Issue by kamilmirza** [xamut/tmux-network-bandwidth#5]
after `Please Wait...`
nothing shows up:
![2020-03-30_23-51-22](https://user-images.githubusercontent.com/6561475/77950113-7f77ff00-72e1-11ea-8973-19acb25c6144.jpg)
all requirement packages are installed 
tmux 2.8 & tmux 3.1rc
working fine on ubuntu 18.04 with tmux 3.0

**Comment by ilya-manin** [comment]
Hey @kamilmirza 

I just checked the plugin on debian (buster) and everything is ok, could you please double-check?
Looks like a problem with the wrong version of awk, please try to install GNU awk.

That's how I checked:

* Create Dockerfile with:
```
FROM debian:buster
RUN apt-get update -qq && apt-get install -y \
      curl \
      gawk \
      git-core \
      net-tools \
      tmux

RUN echo "set -g @plugin 'tmux-plugins/tpm'\n \
set -g @plugin 'xamut/tmux-network-bandwidth' \n \
run -b '~/.tmux/plugins/tpm/tpm' \n \
set-option -g status-interval 3 \n \
set-option -g status-right '#{network_bandwidth}'" > ~/.tmux.conf

RUN git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
RUN TMUX_PLUGIN_MANAGER_PATH="~/.tmux/plugins" ~/.tmux/plugins/tpm/bin/install_plugins

CMD tmux -u # Force UTF8 support
```

* Build the image `docker build -t tmux .`
* Run the container `docker run --rm -ir tmux`
* Then try to download something, like: `curl -O http://dl-cdn.alpinelinux.org/alpine/v3.11/releases/x86_64/alpine-standard-3.11.3-x86_64.iso`

Hope it helps you.

**Comment by kamilmirza** [comment]
fixed it by installing `gawk`
thanks a lot
